baseURL = "https://examplesite.com/"
disableLanguages = []
googleAnalytics = ""
theme = "dot-hugo"
title = "openDOSM"
[Languages.bm]
copyright = "Copyright &copy; 2021 un thème Hugo par [Gethugothemes](https://gethugothemes.com/)"
languageCode = "bm-bm"
languageName = "Bm"
weight = 2
[[Languages.bm.menu.main]]
name = "Accueil"
url = "/"
weight = 1
[[Languages.bm.menu.main]]
name = "Faq"
url = "faq"
weight = 2
[[Languages.bm.menu.main]]
name = "contact"
url = "contact"
weight = 3
[[Languages.bm.menu.main]]
hasChildren = true
name = "docs"
weight = 4
[[Languages.bm.menu.main]]
name = "Installation"
parent = "docs"
url = "installation"
weight = 1
[[Languages.bm.menu.main]]
name = "Billing and Pricing"
parent = "docs"
url = "billing-pricing"
weight = 2
[[Languages.bm.menu.main]]
name = "Features"
parent = "docs"
url = "features"
weight = 3
[Languages.bm.params.banner]
bg_image = "images/banner.jpg"
placeholder = "Avoir une question? Il suffit de demander ici ou de saisir les termes"
subtitle = "Trouvez rapidement des conseils et des réponses auprès de notre équipe d'assistance ou contactez-nous."
title = "Comment pouvons nous aider?"
[Languages.bm.params.cta]
content = "Contactez-nous pour plus de détails sur les services supplémentaires et la tarification du travail personnalisé"
enable = true
title = "Vous n'avez pas trouvé de réponse à votre question?"
[Languages.bm.params.cta.button]
enable = true
label = "Contactez nous"
link = "contact"
[Languages.en]
copyright = "Copyright &copy; CTADR, DOSM 2021 by [Gethugothemes](https://gethugothemes.com/)"
languageCode = "en-us"
languageName = "En"
weight = 1
[[Languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1
[[Languages.en.menu.main]]
name = "Faq"
url = "faq"
weight = 2
[[Languages.en.menu.main]]
name = "contact"
url = "contact"
weight = 3
[[Languages.en.menu.main]]
hasChildren = true
name = "subjects"
weight = 4
[[Languages.en.menu.main]]
name = "Agriculture"
parent = "subjects"
url = "agriculture/agriculture/"
weight = 1
[[Languages.en.menu.main]]
name = "Indices"
parent = "subjects"
url = "indices/indices"
weight = 2
[[Languages.en.menu.main]]
name = "Labour Market"
parent = "subjects"
url = "lmarket/labour-market"
weight = 3
[[Languages.en.menu.main]]
name = "National Accounts"
parent = "subjects"
url = "naccount/national-accounts"
weight = 4
[[Languages.en.menu.main]]
name = "Population"
parent = "subjects"
url = "population/population"
weight = 5
[[Languages.en.menu.main]]
name = "Others"
parent = "subjects"
url = "others/others"
weight = 6
[Languages.en.params.banner]
bg_image = "images/banner.jpg"
placeholder = "Dataset? Just ask here or enter terms"
subtitle = "Find your best data source as you wish.."
title = "Malaysia Open Data Ocean"
[Languages.en.params.cta]
content = "Kindly rectify your dataset keywords."
enable = true
title = "Didn't find any dataset related to your search?"
[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "contact"
[markup.goldmark.renderer]
unsafe = true
[params]
author = "Themefisher"
body_color = "#f9f9f9"
contact_form_action = "#"
description = "This is meta description"
font_family = "lato"
image = "images/logo.png"
light_color = "#f8f9fa"
logo = ""
logo_white = ""
primary_color = "#02007e"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
[[params.social]]
icon = "ti-facebook"
link = "#"
name = "Facebook"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
name = "Twitter"
[[params.social]]
icon = "ti-github"
link = "#"
name = "Github"
[[params.social]]
icon = "ti-linkedin"
link = "#"
name = "Linkedin"
